In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

print(torch.__version__)


2.1.2+cpu


In [6]:
# Introduction to tensors

#  Scalar Tensors

scalar = torch.tensor(7) #pytorch tensors are created using torch.tensor
print(scalar)
print(scalar.ndim)



tensor(7)
0


In [19]:
#  Vector

vector = torch.tensor([7,7])

vectornew = torch.tensor([[7,7,4], [2,4,4] , [4,5,4]  ])

print(vector)
print(vector.ndim)
print(vectornew)
print(vectornew.ndim)
print(vectornew.shape)
print(vectornew[0,0])

tensor([7, 7])
1
tensor([[7, 7, 4],
        [2, 4, 4],
        [4, 5, 4]])
2
torch.Size([3, 3])
tensor(7)


In [22]:
#  Matrix 

matrix = torch.tensor([[1,2],[4,5]])

print(matrix.ndim)
print(matrix[1,1])
print(matrix.shape)

2
tensor(5)
torch.Size([2, 2])


In [26]:
# Tensor

Tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]
                        ]])

print(Tensor.ndim)
print(Tensor.shape)
print(Tensor[0,2])

3
torch.Size([1, 3, 3])
tensor([7, 8, 9])
