In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

Finding Min , Max , Mean , Sum etc (Tensor aggregation)

In [4]:
#  create a tensor

x = torch.arange(0,100 ,10)

print(x)
# find min and max
print(torch.min(x) , x.min())
print(torch.max(x) , x.max() ) 

torch.mean(x.type(torch.float32))


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0) tensor(0)
tensor(90) tensor(90)


tensor(45.)

Finding positional min and max

In [5]:
# Find the position in tensor that has the minimum value with argmin()
x.argmin()
print(x.argmin())

# argmax()

print(x.argmax())


tensor(0)
tensor(9)


* Reshaping - reshape a tensor into desired shape
* view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combined multiple tensors on top of each other
* squeeze - remove all '1' dimensions from a tensor
* unsqueeze - add a '1' dimension to a target tensor
* permute - Return a view of the input with dimensions permuted(swapped) in a certain way


In [6]:
# Reshaping , stacking , squeezing and unsqueezing tensors
y = torch.arange(1. , 11.)
print(y , y.shape)

# add an extra dimension
y_reshaped = y.reshape(5,2)

print(y_reshaped)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


In [25]:
# change the view

z = y.view(2,5)

print(z , z.shape)


tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]]) torch.Size([2, 5])


In [29]:
# Stack tensors on top of each other

y_stacked = torch.stack([y,y,y,y], dim=1)

print(y_stacked)

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])


Torch Squeeze an unsqueeze

In [13]:
# Squeeze method remove all single dimensions

print(y_reshaped , y_reshaped.shape)

print(y_reshaped.squeeze() , y_reshaped.squeeze().shape)

sqz = torch.rand(1,8)
print(sqz.squeeze().shape)


tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]]) torch.Size([5, 2])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]]) torch.Size([5, 2])
torch.Size([8])


In [22]:
# Adding the extra dimension with unsqueeze

print(y_reshaped.unsqueeze(dim=2).shape)

torch.Size([5, 2, 1])


In [25]:
#  Torch permute to shuffle the position 

clr = torch.rand(size=(224, 224,4))

print(clr.shape)

print(clr.permute(2,0,1).shape)

torch.Size([224, 224, 4])
torch.Size([4, 224, 224])


In [1]:
# Indexing (selecting data from tensors)

import torch
x = torch.arange(1,10).reshape(1,3,3)
print(x)

# index of 
print(x[0][0])
print(x[0][0][0])

print(x[: ,: ,1])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([1, 2, 3])
tensor(1)
tensor([[2, 5, 8]])


In [3]:
# Numpy array to tensor

import torch
import numpy as np 

array = np.arange(1,8)
tensor = torch.from_numpy(array)

print(array , tensor)

# Tensors to numpy

tensor = torch.ones(7)
numpy_tnsr = tensor.numpy()

print(numpy_tnsr)


[1 2 3 4 5 6 7] tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32)
[1. 1. 1. 1. 1. 1. 1.]


Reproduciblity (Trying to take random out of random)

In short how a neural network learns:

In [23]:
#  random seed
a = torch.rand(3,4)
b = torch.rand(3,4)

print(a)
print(b)
print(a == b)

tensor([[0.1153, 0.5415, 0.3858, 0.0386],
        [0.4721, 0.7082, 0.0312, 0.5966],
        [0.6048, 0.0229, 0.2223, 0.3482]])
tensor([[0.0615, 0.8682, 0.3024, 0.4611],
        [0.9162, 0.8129, 0.8826, 0.2757],
        [0.0404, 0.5932, 0.6248, 0.6995]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [31]:
#  Lets make some random but reproducible tensors
#  set the random seeds (manual seed)

RANDOM_SEED = 24
torch.manual_seed(RANDOM_SEED)

c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
d = torch.rand(3,4)
print(c)
print(d)
print(c==d)



tensor([[0.7644, 0.3751, 0.0751, 0.5308],
        [0.9660, 0.2770, 0.3372, 0.8910],
        [0.4304, 0.3090, 0.3993, 0.5183]])
tensor([[0.7644, 0.3751, 0.0751, 0.5308],
        [0.9660, 0.2770, 0.3372, 0.8910],
        [0.4304, 0.3090, 0.3993, 0.5183]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [32]:
torch.cuda.is_available()

False