In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot

Random Tensors

Random tensors are important because the way many neural networks learn is that they start tensors full of random numbers and then adjust those random numbers to better represent the data

In [7]:
#  Create a random tensors using pytorch of shape (3,4)

random_tensor = torch.rand(3,4 )

print(random_tensor)
print(random_tensor.ndim)

tensor([[0.8851, 0.9925, 0.0789, 0.2841],
        [0.0298, 0.7255, 0.7878, 0.0726],
        [0.7838, 0.2365, 0.1850, 0.7478]])
2


In [10]:
#  Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3))
print(random_image_size_tensor.shape , random_image_size_tensor.ndim )

torch.Size([224, 224, 3]) 3


In [12]:
# Zeros and ones  
# create a tensor of all zeros

Zero_Tensor = torch.zeros(3,4)

print(Zero_Tensor)

Ones = torch.ones(3,4)
print(Ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Creating Range of Tensors and tensors-like

In [16]:
#  use torch.range()

tens_arrange = torch.arange(1,11)
steparrange = torch.arange(start=3 , end=24 , step=2)

print(tens_arrange.ndim)
print(steparrange)



1
tensor([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])


In [19]:
#  Creating tensors like
tenzeros = torch.zeros_like(tens_arrange)
print(tenzeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


Tensor Data Types

3 big issues in dealing with tensors are
a. Tensors are not right datatype
b. Tensors not right shape
c. Tensors not on the right device

In [21]:
#  float 32 tensor

float_32_tnsr = torch.tensor([[1.2 ,2.1 ,3] ,[2.5, 3.02 , 6.7] ] 
                             , dtype=torch.float16, 
                             device=None,
                             requires_grad=False
                             )
print(float_32_tnsr.dtype)

torch.float16


In [26]:
float_16_tensor = float_32_tnsr.type(torch.float32)
print(float_16_tensor.dtype)
print(float_16_tensor)
# print(float_32_tnsr)

torch.float32
tensor([[1.2002, 2.0996, 3.0000],
        [2.5000, 3.0195, 6.6992]])


In [28]:
int32_tnsr = torch.tensor([3,5,6] , dtype=torch.int32)

multiple = float_16_tensor * int32_tnsr

print(multiple)
print(multiple.dtype)

tensor([[ 3.6006, 10.4980, 18.0000],
        [ 7.5000, 15.0977, 40.1953]])
torch.float32


In [36]:
#  Create a tensor 
some_tnsr = torch.rand(3,4)

print(some_tnsr)
print(f"data type of tensor is {some_tnsr.dtype}")
print(f"shape of tensor is :- {some_tnsr.shape}")
print(f"Device on tensor is {some_tnsr.device}")

tensor([[0.2197, 0.1709, 0.1846, 0.0560],
        [0.2447, 0.8298, 0.5465, 0.5698],
        [0.6937, 0.3672, 0.4215, 0.6789]])
data type of tensor is torch.float32
shape of tensor is :- torch.Size([3, 4])
Device on tensor is cpu


Tensors operation includes

* Addition 
* Substraction 
* multiplicatio
* Division
* Matrix Multiplication

In [42]:
#  Manipulating the tensors

t1 = torch.tensor([3,4,5])
print(t1 +100) 
t2 = torch.tensor([[5,6,7] , [1,2,3] , [3,4,5]] )

print(t1 * t2)

t3 = torch.matmul(t1 ,t2)
print(t1.shape , t2.shape , t3.shape)
print(t3)




tensor([103, 104, 105])
tensor([[15, 24, 35],
        [ 3,  8, 15],
        [ 9, 16, 25]])
torch.Size([3]) torch.Size([3, 3]) torch.Size([3])
tensor([34, 46, 58])


In [5]:
tensornew = torch.rand(5,6,7,8)

# print(tensornew)
# print(tensornew.ndim)

print(torch.matmul(torch.rand(5,2) ,torch.rand(2,6) ))

tensor([[0.5726, 0.7304, 0.5427, 0.4599, 0.6189, 0.3078],
        [0.3984, 0.4439, 0.4058, 0.3582, 0.3265, 0.2151],
        [0.7141, 1.0250, 0.6266, 0.5055, 0.9568, 0.3821],
        [0.3230, 0.3345, 0.3402, 0.3055, 0.2235, 0.1748],
        [0.8359, 0.7617, 0.9264, 0.8528, 0.4100, 0.4540]])


Transpose of tensors in pytorch

In [12]:
tensor_a = torch.tensor([[2,3,] , [4,5,] ,[6,8,] ])

print(tensor_a)

print(tensor_a.shape)

tensor_b = tensor_a.T
print(tensor_b)
print(tensor_b.shape)

tensor([[2, 3],
        [4, 5],
        [6, 8]])
torch.Size([3, 2])
tensor([[2, 4, 6],
        [3, 5, 8]])
torch.Size([2, 3])
